### ISSUE TITLE
it's not a __secure__ couchapp. 

### ISSUE THREAD

**Issue by brunopedroso** [Smileupps/couchapp-chatty#1]
Sorry, but it's not a **secure** couchapp. 

You claim that your app has these features:
- frontend access is restricted to authorized users **only**
- users have access to their own data **only**

... but that's not true. Couchdb has a minimalist authorization model that your app certainly inherits: every authenticated user car read and write any document in the database.

The UI, using the rewrite and the filter, certainly does not show me messages (and any other docs) that don't belongs to me. But nothing prevents me to access the database directly (even navigating with futon) and read all the messages in the database.

Have I missed something?
Should not you, at least, make a big disclaimer on your readme?

**Comment by giowild** [comment]
Hi,

when using manual installation, it's secure as soon as you take the extra proxy step(no. 9)  just added to the readme file.

**Comment by brunopedroso** [comment]
thanks for clarifying! =)

Btw, I suppose the smileupps hosting already takes this step of only reaching database for rewritten urls. Am I right?

**Comment by giowild** [comment]
Exactly, this kind of automation on smileupps is also the reason why I completely forgot to mention this step within the readme. Btw I also hope to have more time to detail this step even better in the future...

Thanks for your useful message!

**Comment by brunopedroso** [comment]
Oh, one last thing: in the tutorial you also claim "requires official CouchDB releases only" as a key strength. Maybe you should review that too.

Sorry to insist on this. That's because I'm studying couchdb for the first time now, and evaluating it for a project. Yesterday it took me some precious time to be sure about this point. 

It's been a very useful exercise, however, and I must say your article and example app are great work. Well done. Thanks. =)
